- src/entities/funding.entity.ts
#14 와 같이, `JoinColumn` 데코레이터를 사용하여 `fundUserUserId` 이랬던 컬럼 이름을 `fundUser`로 변경했습니다.
> before
> after
> fix(funding.entity): Add JoinColumn to tell ORM to set proper column name

- src/app.module.ts
- src/filters/giftogether-exception.filter.ts
- src/transform/transform.interceptor.ts
응답 및 예외 발생 시 클라이언트에게 전달되는 response.timestamp가 timezone이 반영되도록 변경
> feat: add getNow() for timestamp handling in interceptors and filters

- src/entities/funding.entity.ts
- src/entities/gratitude.entity.ts
- src/entities/image.entity.ts
- src/enums/default-image-id.ts
- src/enums/error-code.enum.ts
- src/enums/error-message.enum.ts
- src/enums/image-type.enum.ts
- src/features/funding/dto/create-funding.dto.ts
- src/features/funding/dto/funding.dto.ts
- src/features/funding/funding.module.ts
- src/features/funding/funding.service.ts
- src/features/gift/dto/request-gift.dto.ts
- src/features/gift/gift.module.ts
- src/features/gift/gift.service.ts
- src/features/gratitude/dto/gratitude.dto.ts
- src/features/gratitude/gratitude.controller.ts
- src/features/gratitude/gratitude.module.ts
- src/features/gratitude/gratitude.service.ts
- src/filters/giftogether-exception.ts
이젠 펀딩 객체 생성시 `fundImgUrl`이 존재하면 Image 테이블에 subId를 가진 상태로 row를 추가합니다.
펀딩 객체 가져올 때 제일 먼저 `defaultImgId`가 NULL인지 확인하여 이미지 참조 id를 결정합니다.
- 만약 NULL이라면, Image 테이블의 subid & imgType 필드를 사용하여 이미지를 가져옵니다.
- NULL이 아니라면, Image 테이블의 imgId 필드를 사용하여 이미지를 가져옵니다.
이젠 Gratitude 객체 생성시 `gratImgUrl`이 존재하면 Image 테이블에 subId를 가진 상태로 row를 추가합니다.
이젠 Gratitude 객체 가져올 때 제일 먼저 `defaultImgId`가 NULL인지 확인하여 이미지 참조 id를 결정합니다. Funding Retrieval과 동일합니다.
> Default Image & (get, create) on Gratitude, Funding

- src/entities/rolling-paper.entity.ts
- src/entities/user.entity.ts
- src/enums/default-image-id.ts
- src/features/donation/donation.module.ts
- src/features/donation/donation.service.ts
- src/features/donation/dto/create-donation.dto.ts
- src/features/rolling-paper/dto/create-rolling-paper.dto.ts
- src/features/rolling-paper/dto/rolling-paper.dto.ts
- src/features/rolling-paper/rolling-paper.controller.ts
- src/features/rolling-paper/rolling-paper.module.ts
- src/features/rolling-paper/rolling-paper.service.ts
rolling paper가 혼자서만 생성이 될 수는 없고, donation 생성과 같이 따라가기 때문에 조금 어려웠습니다. donation 생성시 rolling paper가 동시에 생기게 되고, 여기에서 guest 유무에 따라서 동작하게 만들어놓았습니다.
본래의 업무였던 `defaultImgId` 필드는 생성하였고, 영향을 받는 엔티티는 `RollingPaper`와 `User` 입니다. 뜬금없이 `User` 엔티티가 나온 이유는, guest에 `userEmail` 필드가 없는데 nullable이 false라서 게스트 유저가 생성이 안됐습니다.
> WISH-121-rolling_paper-default-image

- src/features/auth/auth.service.ts
- src/features/auth/dto/login.dto.ts
일반 이메일 회원가입 유저들이 login이 안되는 문제를 발견했습니다. login 서비스에서 `isValidPassword` 함수를 호출할때 인자 순서가 바뀌어 있었던 문제입니다. [bcrypt](https://www.npmjs.com/package/bcrypt) 참조
이제는 아래와 같이 잘 됩니다.
> WISH-190-logindto

- src/features/funding/funding.controller.ts
- src/features/funding/funding.service.ts
- src/features/user/user.controller.ts
- 펀딩 리스트 조회시 무한 스크롤을 위해 전달하는 마지막 조회된 펀딩의 id를 전달해왔다.
그렇게 되면 다음 페이지 요청시에 query Parameter에 fundId가 노출된다.
response에 fundId 대신 fundUuid 전달하도록 변경
- 비회원용 펀딩 리스트 조회 API 추가
> fix(funding)

- package-lock.json
- package.json
- src/app.module.ts
- src/features/funding/funding.module.ts
- src/features/funding/funding.tasks.service.ts
추가된 의존성: `@nestjs/schedule`
참조한 문서: <https://docs.nestjs.com/techniques/task-scheduling>
매일 자정 마감된 펀딩들에 대하여 FundClose 이벤트를 발생시킵니다. 이벤트가 발생한 시점의 전날 펀딩만 가지고 옵니다.
> WISH-183-task-scheduling

- src/features/auth/auth.controller.ts
- src/main.ts
소셜 로그인시 redirect와 set-cookie할때 브라우저가 쿠키를 저장하지 못하는 문제를 해결했습니다. 원인은 FE는 HTTPS를 사용하나 BE가 HTTP를 사용하기 때문이었습니다. 아래 순서대로 BE 서버에 SSL 인증서 적용했습니다
1. [Certbot](https://certbot.eff.org/instructions?ws=other&os=ubuntufocal&tab=standard)을 사용하여 SSL 인증서를 받았습니다.
2. 배포환경의 .env 파일에 DEBUG, SSL_CERTIFICATE_LOCATION, SSL_KEY_LOCATION key-value 쌍 추가했습니다.
3. [nestjs / https](https://docs.nestjs.com/faq/multiple-servers) 문서를 참고하여 Nest Factory 생성시 httpsOptions 추가했습니다. (이때 DEBUG 여부 파악)
아래와 같이 쿠키 옵션을 사용하면 됩니다:
```typescript
private cookieOptions = {
httpOnly: true,
path: '/',
secure: true,
// sameSite: 'none' as 'none', // 크로스 도메인 요청을 허용하기 위해 none으로 설정
domain: '.giftogether.co.kr' // 애플리케이션 도메인으로 설정
};
```
www.giftogether.co.kr/login 에서 소셜 로그인 진행시 redirect 돌아오고 나서 개발자 도구의 Application 탭을 캡쳐한 결과입니다.
> feat(ssl): 소셜 로그인 시에 브라우저가 쿠키를 저장하지 못하는 문제 해결 feat. certbot

- src/features/gratitude/gratitude.service.ts
createGratitude 메서드는 아래 코드를 사용하여 gratitude 레코드를 저장함과 동시에 gratitude 인스턴스를 받아온다.
```typescript
const insertResult = await this.gratitudeRepo.insert(
new Gratitude(
funding.fundId,
gratitudeDto.gratTitle,
gratitudeDto.gratCont,
),
);
const grat = insertResult.generatedMaps[0] as Gratitude;
```
문제는 여기에서 grat 인스턴스는 디버그시 regAt, isDel 만 가지고 있었다. 우리가 원하던 gratId는 없었다.
```typescript
let array = [];
const images = [...];
array.push(images.map((i) => i.imgUrl); // [[...]]
array.push(...images.map((i) => i.imgUrl); // [...]
```
따라서 Spread Syntax `...`를 사용해주어야 한다.
> WISH-275-fix-create-gratitude

- src/entities/comment.entity.ts
- src/enums/error-code.enum.ts
- src/enums/error-message.enum.ts
- src/features/comment/comment.controller.ts
- src/features/comment/comment.module.ts
- src/features/comment/comment.service.ts
- src/features/comment/dto/create-comment.dto.ts
- src/features/comment/dto/get-comment.dto.ts
- src/filters/giftogether-exception.ts
Comment API를 최신화 하고 Auth Guard를 붙여 로그인 된 유저만 댓글을 CUD 할 수 있게 했습니다. 본인이 쓴 댓글만 Update Delete 할 수 있게 만들었습니다.
> WISH-257-comment-auth-guard

- src/features/comment/comment.service.ts
funding이 null인데 comments 프로퍼티를 찾으려고 했기 때문입니다. 따라서 ?. 연산자를 사용하여 자동으로 null로 fallback 하고 뒤에 ?? 연산자를 사용하여 빈 배열을 반환하도록 바꿨습니다
```typescript
funding?.comments.map(convertToGetCommentDto) ?? [];
```
쿼리빌더를 사용하여 funding과 comment를 조인하는데 `comment.isDel`이 false인 comment만 가지고 오도록 수정했습니다.
이전 코드에서는 `funding`이 null이 되는 경우가 있었는데, 쿼리를 잘못 짜 "모든 `comment.isDel`이 반드시 false여야 하는" 경우였습니다. 추가적으로 funding이 실제로 존재하지 않은 경우 에러를 throw 하도록 코드를 추가했습니다.
> 예시 응답
```json
{
"timestamp": "2024-08-31T23:24:47.444Z",
"message": "success",
"data": [
{
"comId": 39,
"content": "Quam et labore beatae aut qui. Sint non officiis non aut natus ut. Vero repellendus et veniam sint nobis assumenda quis recusandae earum. Non architecto doloribus praesentium itaque magnam et. Adipisci omnis eius et necessitatibus quo cumque quos …
```
> Hotfix(comment) Null 참조 에러

- src/features/image/image.controller.ts
- src/features/image/image.module.ts
제목이 전부 설명을 합니다. 이젠 Authorization 헤더에 액세스 토큰이 담겨야 이미지 업로드가 가능합니다.
회원가입시 프로필 이미지를 기본 이미지로 설정한 뒤 프로필 페이지에 가서 이미지를 변경하거나 `/signup/extra`에 가서 이미지를 변경하는 방법말고는 없을 것 같습니다.
> ✨ feat(image): Add auth guard to uploadFiles

- src/features/gift/gift.controller.ts
- src/features/gift/gift.service.ts
**createOrUpdateGift 요청 시, 기존 funding과 연결된 Gift들 중 RequestGiftDto[]에서 없어진 Gift는 삭제되도록 로직 추가**
1. 기존 Funding에 연결된 모든 Gift 조회
```typescript
// 기존 Funding에 연결된 모든 Gift 조회
const existingGifts = await this.giftRepository.find({
where: { funding: { fundId: funding.fundId } },
});
// 삭제할 Gift를 추적하기 위한 Set
const existingGiftIds = new Set(existingGifts.map(gift => gift.giftId));
```
2. 요청된 Gift 목록을 업데이트하거나 새로운 Gift를 추가하기 위해 gifts를 순회하면서 요청으로 들어온 Gift의 giftId 목록 추출
```typescript
// 요청된 Gift 목록을 순회하면서 업데이트하거나 새로운 Gift를 추가
const resultGifts = await Promise.all(
gifts.map(async (gift) => {
if (gift.giftId) {
// giftId가 존재하면 기존 Gift를 업데이트
const updatedGift = await this.updateGift(funding, gift);
existingGiftIds.delete(gift.giftId); // 업데이트된 Gift는 삭제 대상에서 제외
return updatedGift;
} else {
// giftId가 없으면 …
```
> feat(gift): add deleteGift in createOrUpdateGift WISH-289

- src/entities/gift.entity.ts
- src/enums/error-code.enum.ts
- src/enums/error-message.enum.ts
- src/features/funding/funding.module.ts
- src/features/funding/funding.service.ts
- src/features/gift/gift.module.ts
- src/features/gift/gift.service.ts
- src/features/image/dto/image.dto.ts
- src/features/image/dto/url.dto.ts
- src/features/image/image.controller.ts
- src/features/image/image.module.ts
- src/features/image/image.service.ts
- src/features/image/s3.service.ts
- src/features/user/user.module.ts
- src/filters/giftogether-exception.ts
- 현재 인증된 모든 유저는 이미지 URL만 안다면 S3 객체를 삭제할 권한을 가지고 있습니다. ⇒ Image 테이블에 userId 컬럼을 추가하는 기능을 구현할 예정입니다.
- 이미지 테이블에 이미지를 제거하는 `ImageService.delete` 메서드를 작성했습니다. 리소스 삭제시 연쇄적으로 Image 레코드를 제거하고 싶다면 이 메서드를 주입하여 사용하세요.
이미지 생성 후 연관 리소스와 관계를 생성하는 기능을 추가할수도.. `link` 메서드를 사용하면 될 듯 하다.
이미지가 S3에 존재하지 않는 경우 => 404
이미지가 S3에 존재하는 경우 => 200
FundingService.remove에서 이미지를 unlink 하고 delete하는 코드를 추가했습니다.
```typescript
await this.imgService.delete(ImageType.Funding, funding.fundId);
```
`delete` 퍼블릭 메서드를 추가하여 funding.service.delete에서 이를 사용합니다.
```typescript
async delete(...gifts: Gift[]): Promise<Gift[]> {
const deleteImgPromises = gifts.map(async (g) =>
this.imgService.delete(ImageType.Gift, g.giftId),
);
Promise.all(deleteImgPromises);
return this.giftRepository.remove(gifts);
}
```
**[펀딩 생성시]**
funding과 연관 gift들: …
> WISH-285-image-deletion

- src/entities/image.entity.ts
- src/entities/user.entity.ts
- src/features/image/image.controller.ts
- src/features/image/image.module.ts
- src/features/image/image.service.ts
- src/features/image/image2.controller.ts
[WISH-292 "유저는 자기가 만든 이미지만 삭제 가능하게 강제해야 합니다"](https://wishfund.atlassian.net/browse/WISH-292) 지라 스토리에 대한 코드 기여 입니다. image delete시에 `image.service.deleteByUrlAndUser`를 사용하여 req.user가 업로드한 이미지인지 확인합니다. 
Image 테이블에 `creatorUserId` 컬럼이 생성되었습니다. 현재 dev1 데이터베이스에 적용되어 있습니다.
Image 테이블의 `imgType` NOT NULL 속성이 해제되었습니다.
`src/features/image/image2.service.ts` 파일이 추가되었고 기존 image.service.ts 파일로부터 upload 로직에 내용이 추가되었습니다. [notice](#notice)를 참조하세요.
user entity에 연관 이미지 Array인 `createdImages: Array<Image>`가 추가되었습니다. OneToMany 데코레이터가 달려있습니다.
현재 이미지 업로드 시 DB에 `creatorUserId`가 추가된 임시 인스턴스가 만들어지는 로직을 `src/features/image/image2.service.ts` 파일에 만들어놓았습니다. 하단에 DIFF 결과를 함께 첨부해드립니다. `image.module.ts` 파일의 임포트에 현재 `image2.service.ts`로 변경되어있습니다. 다음 PR이 머지될때 되돌려놓겠습니다.
임시 파일로 만들어놓은 이유는 다름아닌 별개의 브랜치 #WISH-304 로 브랜치 올릴 예정이기 …
> WISH-303-Image-User-Relational-Mapping

- src/features/auth/auth.service.ts
- src/features/funding/funding.service.ts
- src/features/gift/gift.service.ts
- src/features/gratitude/gratitude.service.ts
- src/features/image/image.service.ts
- src/features/rolling-paper/rolling-paper.service.ts
- src/features/user/user.service.ts
- `ImageService.getInstancesBySubId`: `ImageType`과 `subId` 두개의 인자를 받아 FK 관계로 묶여있는 모든 이미지들을 가지고 옵니다.
- `ImageService.getInstanceByPK`: `imgId` PK를 사용하여 이미지를 가지고 옵니다.
- `FundingService`
- `findOne`	
- `create`
- `update`
- `GiftService`
- `getGiftImgUrl`
- `handleGiftRemoval`
- `setDefaultGiftImage`
- `GratitudeService`
- `getGratitude`
- `createGratitude`
- `updateGratitude`
- `UserService`
- `getUserInfo`
- `getOthersInfo`
- `updateUser`
- `deleteUser`
> WISH-306-Refactoring-Image-Get

- src/entities/gift.entity.ts
https://www.notion.so/10-16-0bf6f8d1c9454c8b9f96c53e4647763a?pvs=4
Gift 설명란이 긴 경우 아이템 컴포넌트를 글씨가 삐져나오는 것을 막기 위해서 글자 길이 제한을 두었습니다.
현재 dev1 데이터베이스에만 적용 완료한 상태입니다. PR 머지 이후 postgres 데이터베이스에도 적용 필요합니다.
> 🗃️ feat(gift): Set giftCont length to 20

- .dockerignore
- .gitignore
- Dockerfile
- docker-compose.yml
멀티 스테이지 빌드를 사용하면 최종 이미지 크기를 줄일 수 있다. devDependencies를 포함하지 않고 노드 런타임과 dist 폴더만 존재하는 이미지를 빌드할 경우 얼마나 최적화 할 수 있는지 확인해보자.
```
$ docker images
REPOSITORY          TAG            IMAGE ID       CREATED       SIZE
giftogether-dev     WISH-317       d77b08dfea87   2 days ago    1.49GB
```
```
$ docker image history giftogether-dev:WISH-317
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
d77b08dfea87   2 days ago      CMD ["npm" "run" "start:debug"]                 0B        buildkit.dockerfile.v0
<missing>      2 days ago      RUN /bin/sh -c npm install # buildkit           392MB     buildkit.dockerfile.v0
<missing>      2 days ago      COPY . . # buildkit                             711kB     buildkit.dockerfile.v0
<missing>      2 days ago …
```
> WISH-319-Multi-Stage-Build-Docker-Image

- .github/workflows/deploy.yml
- Dockerfile
main 브랜치로 merge했을때 이미지를 빌드하고 ECR에 푸시하는 액션인 `deploy.yml`을 만들었습니다.
- [deploy.yml](.github/workflows/deploy.yml) 생성.
- Dockerfile에서 pem 키가 복사되는 명령을 제거.
본 변경 사항은 main 브랜치로의 배포 프로세스를 자동화하여 수동 배포 과정에서 발생할 수 있는 오류를 방지하고, 일관된 배포 환경을 구축하기 위함입니다. 워크플로우가 PR 병합 이벤트로 트리거되도록 설정하여, 개발자가 직접 이미지를 푸시할 필요 없이 자동으로 ECR에 반영되도록 했습니다
워크플로우 트리거: main 브랜치로의 푸시 및 main으로의 PR 병합 시 트리거되도록 설정하였습니다.
AWS 인증 설정: GitHub Secrets에 저장된 AWS 인증 정보를 사용하여 안전한 ECR 접근을 설정했습니다.
Docker 이미지 빌드 및 푸시: Docker 이미지를 빌드하고, ECR 레지스트리 URL을 통해 태그를 설정한 뒤, 해당 이미지를 AWS ECR에 푸시하도록 구성하였습니다.
**앞으로 남은 일**
1. @coding-jjun 에게 **레포지토리 시크릿** 추가 요청
1. `deploy.yml`을 메인 브랜치로 올리기 위한 **semver 이미지 태그 적용법** 조사
1. EC2에서 ECR 이미지 **pull 권한 인가** 설정 필요
1. [도커 캐싱으로 빌드 속도 높이기](https://velog.io/@youngeui_hong/Docker-GitHub-Actions-Google-Cloud%EB%A1%9C-Next.js-CICD-%ED% …
> WISH-324 ci: Create deploy.yml

- docker-compose.yml
`app.volumes`에 global-bundle.pem 키를 바인드하도록 추가했습니다. 그리고 `app.image` 이름을 그냥 giftogether가 아닌, 레지스트리까지 포함한 `975050131958.dkr.ecr.ap-northeast-2.amazonaws.com/coding-jjun/giftogether:latest`로 변경하였는데, 아직 태그 latest로의 이미지 덮어씌우기는 이루어지지 않았습니다.
> fix: Add binding for compose

- .github/workflows/deploy.yml
- docker-bake.hcl
이 PR은 GitHub Actions 워크플로우 내에서 Docker 이미지 빌드 및 배포 프로세스를 개선합니다. 주요 변경 사항에는 `docker-bake.hcl` 구성 파일 도입, 동적 태깅 전략, 효율적인 메타데이터 및 빌드 액션 전환이 포함됩니다.
- **동적 이미지 태깅**: `docker/metadata-action` 설정을 통해 여러 태깅 패턴(`semver`, `sha`, 브랜치 기반)을 사용하여 이미지를 동적으로 태깅하도록 업데이트했습니다.
- **레지스트리 시크릿 통합**: 이미지 경로의 하드코딩을 `${{ secrets.REGISTRY }}`로 대체하여 레지스트리 자격 증명을 중앙에서 관리함으로써 보안과 유연성을 강화했습니다.
- **효율적인 Docker 이미지 빌드 및 푸시**: `docker/bake-action@v5`를 사용해 빌드 및 푸시 단계를 통합하고, 별도의 Docker Bake 설정 파일(`docker-bake.hcl`)에서 타겟을 지정하여 워크플로우를 간소화하고 다중 플랫폼 빌드를 지원했습니다.
- **새로운 Docker Bake 파일**: Docker 이미지에 대해 빌드 컨텍스트, Dockerfile 위치 및 플랫폼 타겟을 구성하는 `docker-bake.hcl` 파일을 도입했습니다. 이 구성 파일은 다중 플랫폼 지원(예: `linux/amd64`)을 가능하게 하고, 각 단계에 일관된 빌드 매개변수를 재사용할 수 있게 합니다.
- **보안 및 유연성 강화**: 레지스트리 자격 증명을 중앙 관리하고 이미지를 동적으로 태깅하여 더 안전하고 유연한 워크플로우가 가능합니다.
- …
> WISH-330-tags and image push

- src/entities/notification.entity.ts
- src/features/notification/dto/notification.dto.ts
- src/features/notification/notification.controller.ts
- src/features/notification/notification.service.ts
- Notification Entity에 isRead Column 추가
- PATCH /notification/read API 추가
> 알림 히스토리 페이지 방문시각 이전에 생성된 읽지 않은 알림 모두 읽음 상태로 변경
- GET /notification/read API 추가
> 마지막으로 생성된 알림의 읽음 상태 조회
> 읽지 않은 알림이 있으면 true 반환
> 읽지 않은 알림이 없으면 false 반환
> Notification

- .github/workflows/deploy-to-ec2.yml
본 코드수정은 EC2에서 최신화 되어있지 않은 파일, 특히 auto-deploy.sh 를 사전에 미리 동기화 한 후 배포를 진행하기 위해 필요합니다.
> WISH-339-auto-git-pull-on-ec2

- src/features/comment/comment.service.ts
이 PR은 Giftogether 서비스에서 댓글 응답의 authorName 속성이 항상 “ANONYMOUS”로 표시되던 버그를 수정합니다. 댓글을 조회하는 쿼리에서 author 관계를 올바르게 조인하도록 수정하여 이 문제를 해결했습니다.
변경 사항:
CommentService의 getComment 쿼리에 author 관계에 대한 leftJoinAndSelect를 추가했습니다.
수정 전:
모든 응답에서 authorName이 실제 사용자와 관계없이 “ANONYMOUS”로 잘못 표시되었습니다.
```json
{
"timestamp": "2024-11-27T22:11:03.728Z",
"message": "success",
"data": [
{
"comId": 108,
"content": "Aut at veritatis totam. Ab reprehenderit dolor quod harum tempora provident aut quo et. Dolore corrupti laboriosam quo libero ex sit saepe. Animi amet modi eos sit doloremque est rerum. In delectus aut quae.",
"regAt": "2024-11-27T04:10:59.785Z",
"isMod": false,
"authorId": 140,
"authorName": "ANONYMOUS"
}
]
}
```
수정 후:
authorName이 이제 댓글 작성자의 이름을 정확히 반영합니다.
```json
{
"timestamp": "2024-11-30T21:39:57.806Z", …
```
> WISH-369 Fix: /comment GET API authorName problem 해결 🎉

- src/entities/funding.entity.ts
- src/entities/gift.entity.ts
- src/entities/user.entity.ts
---
이 PR은 Giftogether 서비스에서 엔티티 관계 설정 문제로 인해 데이터베이스 스키마에 예상치 못한 `defaultImgIdImgId` 열이 생성되는 문제를 해결합니다. 영향을 받는 엔티티에서 `@JoinColumn` 데코레이터를 사용하여 올바른 열 이름(`defaultImgId`)을 명시적으로 지정하여 문제를 해결했습니다.
- 다음 엔티티의 `defaultImgId` 속성에 `@JoinColumn({ name: 'defaultImgId' })` 추가:
- `Funding`
- `Gift`
- `User`
데이터베이스 스키마에 불필요하고 의도하지 않은 `defaultImgIdImgId` 열이 생성되었습니다.
**gift**
```
pg:postgres@db-server/postgres=> \d gift
table "public.gift"
Name        |         Type          | Nullable |                Default
-------------------+-----------------------+----------+----------------------------------------
giftId            | integer               | "NO"     | nextval('"gift_giftId_seq"'::regclass)
giftUrl           | character varying     | "NO"     |
giftOrd           | integer               | "NO"     | …
```
> WISH-360-defaultImgIdImgId

- src/entities/funding.entity.ts
- src/entities/gift.entity.ts
- src/entities/user.entity.ts
`@OneToOne` 데코레이터가 자동으로 Unique Constraint를 달아버리는 문제 때문에 `@ManyToMany` 데코레이터로 변경합니다.
> FIX-defaultImgId

- src/main.ts
이 PR은 NestJS 프로젝트의 `src/main.ts` 파일에서 CORS 정책 구성을 수정하여 유연성과 보안을 강화합니다. 기존의 정적인 `CORS_ORIGIN` 설정을 보다 강력한 검증 로직으로 대체하여 동적으로 처리합니다.
- **동적 Origin 검증:**  
이제 `CORS_ORIGIN` 환경 변수를 쉼표로 구분된 허용된 Origin 목록으로 구문 분석합니다. 이 목록은 들어오는 요청에 대해 동적으로 검증됩니다.
- **향상된 오류 처리:**  
허용된 목록에 없는 Origin에서의 요청은 `Not allowed by CORS`라는 설명이 포함된 오류 메시지를 반환합니다.
- **의존성 주입 사용:**  
`ConfigService`를 활용하여 `CORS_ORIGIN` 환경 변수를 가져오고 구문 분석하며, NestJS의 의존성 주입 시스템을 통해 더 나은 설정 가능성과 모듈화를 제공합니다.
- **보안 강화:** 동적 검증을 통해 명시적으로 허용된 Origin만 요청을 보낼 수 있도록 하여, 허가되지 않은 크로스 오리진 접근 위험을 줄입니다.
- **유연성:** 이제 `CORS_ORIGIN` 환경 변수에 쉼표로 구분된 여러 Origin을 지정할 수 있습니다.
- **유지 보수성:** `ConfigService`를 통해 중앙 집중식 구성 관리를 수행하여 확장 가능하고 유지 보수 가능한 애플리케이션의 모범 사례를 따릅니다.
1. `CORS_ORIGIN` 환경 변수에 허용된 Origin 목록을 쉼표로 구분하여 설정합니다(예: …
> WISH-374-cors_origin

- src/app.module.ts
- src/enums/error-code.enum.ts
- src/enums/error-message.enum.ts
- src/enums/provisional-donation-status.enum.ts
- src/features/deposit/commands/match-deposit.usecase.spec.ts
- src/features/deposit/commands/match-deposit.usecase.ts
- src/features/deposit/commands/upload-deposit.usecase.spec.ts
- src/features/deposit/commands/upload-deposit.usecase.ts
- src/features/deposit/deposit.module.ts
- src/features/deposit/deposit.service.ts
- src/features/deposit/domain/entities/deposit.entity.ts
- src/features/deposit/domain/entities/provisional-donation.entity.ts
- src/features/deposit/domain/events/deposit-event.handler.spec.ts
- src/features/deposit/dto/deposit.dto.ts
- src/features/deposit/queries/find-provisional-donations-by-sender-sig.usecase.ts
- src/features/donation/donation.service.ts
- src/features/funding/funding.module.ts
- src/filters/giftogether-exception.ts
- src/tests/create-mock-repository.ts
- src/tests/data-source-options.ts
이번 PR에서는 기부금 매칭 및 관리 로직의 주요 업데이트가 이루어졌습니다. 다음의 주요 기능 및 코드 변경 사항이 포함됩니다:
1. **Deposit 및 ProvisionalDonation 엔티티 리팩토링**  
- TypeORM 엔티티로 등록하여 데이터베이스와 연동 가능하도록 수정했습니다.  
- 각 엔티티에 상태 전이 메서드 (`approve`, `reject`, `refund` 등)를 추가하여 상태 관리 로직을 강화했습니다.  
- 상태 전이 로직에 예외 처리를 추가하여 잘못된 상태 전이를 방지했습니다.
2. **새로운 유스케이스 추가**  
- `FindProvDonationsBySenderSigUseCase`를 구현하여 `senderSig` 기반으로 ProvisionalDonation을 검색할 수 있도록 했습니다.  
- 이 유스케이스는 `MatchDepositUseCase`에서 사용됩니다.
3. **기능 확장 및 코드 리팩토링**  
- `MatchDepositUseCase` 및 `UploadDepositUseCase`에서 기존의 메모리 기반 레포지토리를 제거하고, TypeORM 기반 레포지토리로 대체했습니다.  
- `execute` 메서드가 비동기로 변경되어 데이터베이스 작업을 처리할 수 있도록 개선했습니다.  
- `DepositDto`의 `sender` 필드를 `senderSig`로 변경했습니다.
4. **Error Code 및 Error Message 추가**  
- 상태 전이와 관련된 새로운 에러 코드(`1600`) 및 메시지를 추가했습니다.
5. **기타**  
- 기존 …
> WISH-386 migration: ProvisionalDonation, Deposit

- src/enums/noti-type.enum.ts
- src/features/deposit/commands/match-deposit.usecase.spec.ts
- src/features/deposit/commands/match-deposit.usecase.ts
- src/features/deposit/deposit.module.ts
- src/features/deposit/domain/events/deposit-event.handler.spec.ts
- src/features/deposit/domain/events/deposit-event.handler.ts
- src/features/deposit/domain/events/deposit-partially-matched.event.ts
- src/features/deposit/queries/find-provisional-donations-by-sender-sig.usecase.ts
1. **새로운 알림 유형 추가**:
- `DonationPartiallyMatched`: 입금 금액이 불일치할 경우의 알림 유형 추가.
2. **비효율적인 유스케이스 제거**:
- `FindProvDonationsBySenderSigUseCase` 유스케이스가 제거되었습니다.
- 단순한 레코드 조회는 TypeORM의 기본 기능을 사용하여 대체.
3. **비즈니스 로직 업데이트**:
- 부분 매칭 로직 개선:
- 매칭되지 않는 경우에도 알림을 통해 정확한 상태 전달.
- 관리자에게 알림 발송 추가.
- `DepositPartiallyMatchedEvent`에 `ProvisionalDonation` 데이터 포함.
4. **테스트 및 핸들러 추가**:
- `DepositEventHandler`의 부분 매칭 이벤트 로직에 대한 테스트 케이스 추가.
- 관리자 및 후원자 알림 검증.
1. **`noti-type.enum.ts`**:
- 새로운 알림 유형 `DonationPartiallyMatched` 추가.
2. **`match-deposit.usecase.ts`**:
- `FindProvDonationsBySenderSigUseCase` 제거.
- 비즈니스 로직 단순화 및 명확화.
3. **`deposit-event.handler.ts`**:
- 부분 매칭 이벤트 핸들링 구현:
- `ProvisionalDonation` 상태 반려.
- 관리자와 후원자 알림 발송.
4. **`deposit-partially-matched.event.ts`**:
- `DepositPartiallyMatchedEvent`에 …
> WISH-383 DonationPartiallyMatched Handler

- src/features/comment/comment.module.ts
- src/features/comment/comment.service.ts
- src/features/comment/dto/get-comment.dto.ts
댓글 기능에서 사용자 프로필 이미지를 연동하고, 관련된 이미지 처리 로직을 추가했습니다. 이 변경으로 댓글 데이터에서 사용자 프로필 이미지 URL을 제공할 수 있으며, UI에서 이를 활용해 사용자 경험을 개선할 수 있습니다.
1. **댓글 모듈 수정**
- `ImageModule`을 `CommentModule`의 import에 추가했습니다.
2. **댓글 서비스 수정**
- `ImageInstanceManager`를 의존성으로 주입하여 사용자 프로필 이미지를 처리.
- 댓글 작성, 수정, 삭제 및 조회 시 `author.image` 필드에 사용자 프로필 이미지 정보를 추가.
- `findMany` 메서드에서 QueryBuilder를 사용하여 사용자 이미지 데이터를 매핑.
3. **DTO 수정**
- `GetCommentDto`에 `authorImg` 필드 추가.
- 댓글 조회 시 사용자 프로필 이미지 URL 반환.
4. **QueryBuilder 로직 강화**
- `author.image`를 동적으로 매핑하기 위한 조건 추가:
- 기본 이미지(`defaultImgId`)가 설정된 경우 해당 이미지를 반환.
- 기본 이미지가 없을 경우, 사용자 ID와 이미지 타입을 기준으로 이미지를 매핑.
- 댓글 작성, 조회, 수정, 삭제 시 사용자 프로필 이미지가 올바르게 반환되는지 확인.
- QueryBuilder 로직을 통해 사용자 이미지 데이터가 정확히 매핑되는지 검증.
- 기존 기능이 변경 사항으로 인해 영향을 받지 않는지 확인.
- …
> WISH-393-Image-URL-in-CommentDto

- src/event-handlers/comment/comment-event-handler.ts
- src/event-handlers/friend/friend-event-handler.ts
- src/event-handlers/fund/fund-event-handler.ts
- src/event-handlers/gratitude/gratitude-event-handler.ts
> feat: add handler
