src/features/user/user.controller.ts
controller의 URL에 'api/' 추가하여 날리는 PR입니다.
=> fix: user controller URL

.gitignore, src/app.module.ts
<https://velog.io/@bshunter/AWS-ec2-rds-no-pghba.conf-entry-%EC%97%90%EB%9F%AC> 블로그를 참조하여 `global-bundle.pem`을 다운받으면 됩니다.
=> hotfix: Resolve RDS authorization error

src/enums/notification.enum.ts
NotResponse = '00', // 요청에 응답하지 않은 상태
Accept = '01', // 요청을 수락한 상태
Refuse = '02', // 요청을 거절한 상태
UnWritten = '03', // 감사인사를 작성하지 않은 상태
Written = '04', // 감사인사를 작성한 상태
=> fix : enum ReqType

src/entities/funding.entity.ts, src/features/funding/funding.controller.ts, src/features/funding/funding.service.ts
=> WISH-61 개별 funding UUID로 조회

src/features/funding/funding.controller.ts, src/features/funding/funding.service.ts
=> WISH-67 feat(funding.create): Change create return data into whole Funding object

src/entities/account.entity.ts
=> feat: account entity

src/main.ts
=> feat: enable CORS

src/features/funding/funding.service.ts
원인
1. await를 안 붙였다.
2. Promise 객체에 인덱스 연산자 `[0]` 를 붙였다.
=> fix(funding.service): funding.create sentinel user 참조 못하는 문제 해결

requirements.txt, scripts/README.md, scripts/usefaker.py, src/app.module.ts, src/entities/image.entity.ts, src/entities/user.entity.ts, src/enums/bank-type.enum.ts
=> WISH-72-dummy-data

src/features/user/user.service.ts
=> fix: deleteUser

src/features/gift/gift.controller.ts, src/features/gift/gift.service.ts
findAllGift
- fundId를 map할 수 없는 에러 발생
→ findAndCount에서 relations: ['funding'] 추가
deleteGift
- softDelete를 진행한 Gift를 giftId로 다시 조회하려 해서 에러 발생
→ delete로 변경
=> fix(gift): add Query relations & remove softdelete WISH-111

src/entities/address.entity.ts, src/features/address/address.controller.ts, src/features/address/address.service.ts, src/features/address/dto/address.dto.ts, src/features/address/dto/create-address.dto.ts, src/features/address/dto/update-address.dto.ts
- Response Address Dto 추가
- Address  Entity에 받는 사람 이름, 번호 추가
=> fix(Address)

src/features/image/dto/image.dto.ts, src/features/image/image.controller.ts, src/features/image/image.service.ts
=> WISH-133-image-many

src/features/user/user.controller.ts, src/features/user/user.service.ts
sample response of `/user/{user:id}`
```json
{
"timestamp": "2024-06-05T01:27:29.750Z",
"message": "사용자 정보 조회에 성공하였습니다.",
"data": {
"userNick": "Ara.Stiedemann",
"userName": "왜 이름도 필수로 집어넣어야 함?",
"userPhone": "221-510-5592",
"userBirth": "1997-09-26",
"authType": "Jwt",
"userImg": "naver.com",
"userId": 12,
"userEmail": "chltmdgus604@gmail.com",
"authId": null
}
}
```
=> WISH-142-User-Read

package-lock.json, package.json, src/features/image/image.controller.ts
이미지 압축 + 크기조정 기능을 추가했습니다. sharp라는 이미지 처리 패키지를 사용했습니다.
> 전: 2.3MB
> 후: 150KB
=> feat(image): Add 'sharp' dependency and Add Image compression feature

src/entities/notification.entity.ts, src/features/friend/dto/friend.dto.ts, src/features/friend/friend.controller.ts, src/features/friend/friend.module.ts, src/features/friend/friend.service.ts, src/features/notification/dto/create-notification.dto.ts, src/features/notification/dto/notification.dto.ts, src/features/notification/dto/update-notification.dto.ts, src/features/notification/notification.controller.ts, src/features/notification/notification.module.ts, src/features/notification/notification.service.ts
- 친구 수락 : userId가 friendId의 요청 수락
1. friendId한테 userId가 수락했다고 알림 생성
2. userId가 friendId한테 받은 친구 신청 알림 변경
a. 알림히스토리에서 친구 수락시 notiId로 알림 ReqType 변경
b. friendId의 프로필에서 수락시 userId, friendId로 noti 검색 후 변경
- 친구 요청 : userId가 friendId한테 친구 요청
1. friendId한테 userId가 친구 요청 보냈다고 알림 생성
=> Notification

src/features/friend/friend.service.ts
=> fix(friend): fix getFriends WISH-166

src/enums/bank-type.enum.ts
- 우체국은행, SBI저축은행, NH투자증권, 전북은행 추가
- 산림조합 삭제
=> fix(bank): add & remove bank WISH-179

src/enums/error-code.enum.ts, src/enums/error-message.enum.ts, src/features/donation/donation.controller.ts, src/features/donation/donation.module.ts, src/features/donation/donation.service.ts, src/filters/giftogether-exception.ts
이미 마감된 펀딩에 대한 donation 생성 시 에러 반환하도록 수정
=> feat(donation): cannot create donation for closed funding

src/features/user/dto/update-user.dto.ts, src/features/user/user.service.ts
UpdateUserDto의 userBirth
IsNotEmpty에서 IsOptional로 변경
=> fix(user): fix UpdateUserDto userBirth IsOptional

src/transform/transform.interceptor.ts
- interceptor 조건문에서 response.message 제거
=> fix(interceptor): remove response.message in conditional

src/features/donation/donation.service.ts, src/features/donation/dto/donation-list.dto.ts, src/features/donation/dto/donation.dto.ts, src/features/user/user.controller.ts
- Query Parameter에 status 추가
> ongoing : 진행중인 펀딩의 donation
> ended : 마감된 펀딩의 donation
- DonationDto 변경
> fundId -> fundUuid로 변경
> donAmnt 추가
> fundUserId, fundUserNick, fundUserImg 추가
=> feat(donation)

src/features/donation/donation.service.ts, src/features/gratitude/dto/get-gratitude.dto.ts, src/features/gratitude/gratitude.service.ts
=> 🎨 feat(GetGratitudeDto): Update from fundId to fundUuid

src/main.ts
본 PR을 적용하고 난 직후에 배포 서버의 .env의 DEBUG를 false로 설정해야 합니다.
=> fix(SSL): Inverse debugOption

src/entities/gratitude.entity.ts, src/features/gratitude/gratitude.controller.ts, src/features/gratitude/gratitude.module.ts, src/features/gratitude/gratitude.service.ts
- 이제 gratitude delete가 soft delete가 아닌, hard delete가 됩니다. soft delete가 의미가 없기 때문입니다. PK로 gratId가 fundId로 되어있으므로 삭제 후 생성시 제거 안하면 unique constraint 에러가 납니다.
=> ✨ feat(auth): Add authorization to Gratitude

src/features/notification/notification.controller.ts, src/features/notification/notification.module.ts
=> feat(notification): add AuthGuard WISH-265

src/enums/error-code.enum.ts, src/enums/error-message.enum.ts, src/features/rolling-paper/rolling-paper.controller.ts, src/features/rolling-paper/rolling-paper.module.ts, src/features/rolling-paper/rolling-paper.service.ts, src/filters/giftogether-exception.ts
이제 펀딩 개설자만이 로그인 후 롤링페이퍼를 받아볼 수 있습니다. [/rollingpaper/{fundUuid}](https://www.notion.so/rollingpaper-fundUuid-6a9ca5415c184509b52e66fad930860d?pvs=21) 에 API 예시 추가했습니다.
=> WISH-251-RollingPaper-auth-guard

src/features/funding/funding.service.ts, src/features/user/user.controller.ts
- 다른 사용자의 진행중/종료된 펀딩 불러오도록 코드 추가
- token.userId와 parameter의 userId 확인해서 친구인지 아닌지 확인 후, 펀딩 공개범위에 맞춰서 펀딩 목록 전달
=> feat(funding): add Read Others' funding API

src/entities/image.entity.ts, src/enums/error-code.enum.ts, src/enums/error-message.enum.ts, src/features/funding/dto/update-funding.dto.ts, src/features/funding/funding.controller.ts, src/features/funding/funding.service.ts, src/features/gift/gift.module.ts, src/features/gift/gift.service.ts, src/features/image/image.controller.ts, src/features/image/image.service.ts, src/filters/giftogether-exception.ts
- `ImageController.uploadFiles`
- `FundingService.create`
- `FundingService.update`
- `GiftService.updateGift`
- `GiftService.handleGiftImageRemoval`
- `GiftService.saveNewImage`
- `GratitudeService`
- `RollingpaperService`
- `UserService`
**funding create**
image upload
funding create
**update gift**
image upload
gift update
=> WISH-304-Refactoring-Image-Save

src/entities/gratitude.entity.ts, src/features/auth/auth.module.ts, src/features/auth/auth.service.ts, src/features/donation/donation.module.ts, src/features/donation/donation.service.ts, src/features/funding/funding.controller.ts, src/features/funding/funding.service.ts, src/features/gift/gift.service.ts, src/features/gratitude/gratitude.controller.ts, src/features/gratitude/gratitude.module.ts, src/features/gratitude/gratitude.service.ts, src/features/image/image.service.ts, src/features/rolling-paper/rolling-paper.module.ts, src/features/rolling-paper/rolling-paper.service.ts, src/features/user/user.service.ts
- `GratitudeService`
- `RollingPaperService`
- `UserService`
=> WISH-308-Refactoring-Image-Save

src/features/donation/donation.service.ts
=> refactor: Change return value from fundId to fundUuid

src/features/user/user.controller.ts
- controller에서 메서드 순서 변경해서 버그 해결
- 요청된 경로와 일치하는 첫 번째 핸들러가 호출되면서 /user/:userId로 읽어서 버그 발생
=> fix(user): getUserAddress, getUserDonation

src/features/address/address.controller.ts
=> feat(address): add UseGuard at delete Address

.dockerignore, .gitignore, .vscode/launch.json, Dockerfile.development, Dockerfile.development.dockerignore, docker-compose.development.yml, package.json
이 풀 리퀘스트는 Dockerfile, launch 구성, docker-compose 설정의 개선이 포함되어 워크플로우를 단순화하고 디버깅을 가능하게 만듭니다.
1. **VSCode Launch 구성 (`.vscode/launch.json`)**:
- Docker Compose와 관련된 `preLaunchTask` 및 `postDebugTask`를 제거했습니다. 별도로 up을 수행하고 디버깅을 attach하는 것이 낫다고 판단했습니다.
2. **개발용 Dockerfile (`Dockerfile.development`)**:
- 레이어 캐싱을 개선하기 위해 `COPY` 명령어를 재정렬했습니다:
- `package*.json`을 개별적으로 복사하는 대신, 하나의 `COPY . .` 명령어로 통합하여 중복을 줄였습니다.
3. **Docker Ignore 파일 (`Dockerfile.development.dockerignore`)**:
- 빌드 컨텍스트에서 불필요한 파일을 제외하기 위해 새로운 `.dockerignore` 파일을 추가했습니다:
- `node_modules`, `.git` 등의 디렉터리를 무시하여 Docker 이미지 빌드 속도를 높이고 크기를 줄였습니다.
4. **개발용 Docker Compose 파일 (`docker-compose.development.yml`)**:
- 볼륨 매핑을 업데이트했습니다:
- 볼륨을 `src`만 읽기 전용 모드로 마운트하여 컨테이너 내 파일을 실수로 수정할 위험을 줄였습니다.
- `/usr/src/app/node_modules` 볼륨을 제거하여 잠재적인 충돌을 방지하고 …
=> 🚑 CI: Fix docker-compose issues

src/features/funding/funding.service.ts
- 마감일 당일인 펀딩은 진행중인 펀딩에서 조회되도록 수정
=> feat(funding): include due date funding in ongoing status

.github/workflows/deploy.yml, src/features/funding/funding.service.ts
이 PR은 EC2 인스턴스에 애플리케이션을 배포하는 새로운 CD 파이프라인을 도입하여 기존 CI 워크플로우와 매끄럽게 통합합니다. 주요 변경 사항은 다음과 같습니다:
- **CI 워크플로우 이름 변경**: `.github/workflows/deploy.yml`을 `.github/workflows/build-and-push-image-to-ecr.yml`로 변경하여 명확성을 높임.
- **의존 워크플로우 추가**: Docker 이미지가 ECR에 푸시된 후 트리거되는 `.github/workflows/deploy-to-ec2.yml` 추가.
- **배포 스크립트 추가**: `auto-deploy.sh`를 추가하여 ECR에서 Docker 이미지를 가져오고 EC2 인스턴스에서 컨테이너를 재시작하는 과정을 자동화.
- **버전 업데이트**: CI 워크플로우에서 `aws-actions/configure-aws-credentials`를 버전 4로 업데이트.
1. CI가 Docker 이미지를 빌드하고 ECR에 푸시합니다 (`main` 브랜치를 대상으로 하는 PR에서 실행).
2. 새로운 배포 워크플로우는 성공적인 CI 실행을 감지하여 다음 작업을 수행합니다:
- SSH를 사용해 EC2 인스턴스에 연결.
- 배포 스크립트를 실행하여 이미지를 가져오고 애플리케이션 컨테이너를 재시작.
[workflow_run](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflo …
=> WISH-331-Continuous Delivery

docker-compose.development.yml
- **fix: Add mount global-bundle.pem on docker-compose.development.ytml**
- **Revert "fix: Add mount global-bundle.pem on docker-compose.development.yml"**
- **Reapply "fix: Add mount global-bundle.pem on docker-compose.development.yml"**
=> global bundle on compose dev

src/features/funding/dto/funding.dto.ts, src/features/funding/funding.service.ts
이 Pull Request는 `FundingDto` 객체에 사용자 프로필 이미지 URL을 포함하는 기능을 추가하여, 펀딩 기능 내에서 사용자 관련 정보를 보다 풍부하게 표시할 수 있도록 개선합니다.
---
1. **`FundingDto` 업데이트**:
- `fundUserImg` 속성을 `FundingDto` 클래스에 추가.
- 생성자를 수정하여 `fundUserImg` 값을 설정하도록 변경.
2. **`FundingService` 리팩토링**:
- `findAllFunding`, `getFundingDetails`, `create`, `update` 메서드를 업데이트하여 `imageManager`를 사용해 사용자 프로필 이미지 URL을 가져오도록 수정.
- `FundingDto`를 생성하기 전에 비동기로 사용자 이미지 URL을 가져오는 로직 추가.
3. **데이터 표시 강화**:
- 펀딩 관련 API 응답에 기존 메타데이터와 함께 사용자 프로필 이미지 URL이 포함되도록 개선.
---
- **하위 호환성 유지**: `fundUserImg`에 대한 기본 경로를 추가하여 기존 API가 중단 없이 원활하게 전환될 수 있도록 함.
- **깔끔한 리팩토링**: 이미지 가져오기 로직을 통합하여 `FundingService` 메서드의 가독성과 유지보수성을 향상.
---
https://wishfund.atlassian.net/browse/WISH-371
같은 `findAll` 리턴구문 중 `new FundingDto`의 인자가 빠져있는 것을 확인하여 `gifts: ResponseGiftDto[]`와 …
=> WISH-334 Giftogether의 FundingDto에 사용자 이미지 추가 🎉

src/features/funding/funding.service.ts
- 오늘 마감중인 펀딩이 종료된 펀딩으로 조회되던 버그 수정
=> fix(funding): set currentDate sharp WISH-338

package.json, src/app.module.ts, src/enums/deposit-status.enum.ts, src/enums/error-code.enum.ts, src/enums/error-message.enum.ts, src/features/deposit/application/usecases/match-deposit.usecase.spec.ts, src/features/deposit/application/usecases/match-deposit.usecase.ts, src/features/deposit/application/usecases/upload-deposit.usecase.spec.ts, src/features/deposit/application/usecases/upload-deposit.usecase.ts, src/features/deposit/deposit.controller.spec.ts, src/features/deposit/deposit.controller.ts, src/features/deposit/deposit.module.ts, src/features/deposit/deposit.service.spec.ts, src/features/deposit/deposit.service.ts, src/features/deposit/domain/entities/deposit.entity.ts, src/features/deposit/domain/entities/provisional-donation.entity.ts, src/features/deposit/domain/events/deposit-event.handler.ts, src/features/deposit/domain/events/deposit-matched.event.ts, src/features/deposit/domain/events/deposit-partially-matched.event.ts, src/features/deposit/domain/events/deposit-unmatched.event.ts, src/features/deposit/dto/deposit.dto.ts, src/features/deposit/infrastructure/repositories/in-memory-deposit.repository.ts, src/features/deposit/infrastructure/repositories/in-memory-provisional-donation.repository.ts, src/filters/giftogether-exception.ts
---
이 PR은 **Deposit 모듈**을 도입하여 입금 내역 업로드 및 예비 후원과의 매칭을 처리하는 기능을 추가합니다. 이 모듈은 서비스, 유스케이스, 엔티티, 리포지토리, 컨트롤러를 포함하며 테스트 커버리지를 제공합니다. 주요 변경 사항은 다음과 같습니다:
---
- **`src/features/deposit/deposit.module.ts`**  
`DepositModule`을 정의하여 입금 처리를 위한 핵심 구성 요소를 연결합니다.
- **`src/features/deposit/deposit.controller.ts`**  
입금 데이터를 업로드하기 위한 엔드포인트를 제공합니다. 주요 기능:
- `POST /deposits/upload`: 입금 데이터를 받아 서비스 계층에서 처리합니다.
- **`src/features/deposit/deposit.controller.spec.ts`**  
`DepositController`에 대한 단위 테스트를 포함합니다.
- **`src/features/deposit/deposit.service.ts`**  
`UploadDepositUseCase`와 `MatchDepositUseCase`를 통합하여 입금 데이터를 처리하고 매칭 로직을 수행합니다.
- **`src/features/deposit/deposit.service.spec.ts`**  
`DepositService`에 대한 테스트가 포함됩니다.
- **`src/features/deposit/application/usecases/upload-deposit.usecase.ts`**  
새로운 …
=> Feat: Deposit Domain Logic PoC

src/entities/donation.entity.ts, src/features/deposit/commands/match-deposit.usecase.spec.ts, src/features/deposit/domain/entities/deposit.entity.ts, src/features/deposit/domain/events/deposit-event.handler.spec.ts, src/features/deposit/domain/events/deposit-event.handler.ts, src/features/donation/commands/create-donation.command.ts, src/features/donation/commands/create-donation.usecase.ts, src/features/donation/donation.service.ts
이 Pull Request에서는 `Donation.create` 메서드를 리팩토링하여 `Deposit` 인스턴스가 반드시 필요하도록 변경했습니다. 이를 통해 기부 데이터와 예치 데이터 간의 관계를 더 명확히 하고, 데이터 무결성을 강화했습니다. 🎉
---
1. **`Donation` 엔티티 업데이트**
- `Deposit` 속성을 `nullable: false`로 설정하여 `Donation`과 항상 연결되도록 강제했습니다.
- `Donation.create` 메서드의 인자 목록에 `Deposit`을 추가했습니다.
2. **`MatchDepositUseCase` 관련 테스트 리팩토링**
- `ProvisionalDonation` 레포지토리 변수명을 더 명확히 수정 (`donationRepository` ➡️ `provDonationRepository`).
- 새로운 테스트 케이스 추가:
- 예치 데이터와 완전히 매칭되는 경우 성공적으로 `ProvisionalDonation`을 생성하는지 확인.
- 일부만 매칭되거나 매칭되지 않는 경우의 실패 시나리오 테스트.
3. **`CreateDonationCommand` 및 관련 핸들러 변경**
- `CreateDonationCommand`에 `deposit` 속성 추가.
- `DepositEventHandler`에서 `CreateDonationCommand` 호출 시 `Deposit` 인스턴스 전달.
4. **기타 리팩토링**
- 기존의 `createDonation` 로직을 리팩토링 또는 주석 처리하여 이후 리팩토링을 위한 준비 작업 수행.
- 기존 메서드 호출부를 …
=> Enhance deposit and donation management features

src/features/auth/auth.controller.ts
이제 디버그 환경에서도 포스트맨 같은걸로 테스트할때 로그인시에 자동으로 쿠키에 잘 담깁니다. `secure` 옵션을 `DEBUG` env에 맞추어 갑니다.
=> feat(auth.controller): cookieOptions.secure DEBUG

src/enums/error-code.enum.ts, src/enums/error-message.enum.ts, src/filters/giftogether-exception.ts
Remove a circular import in the exception handling and add new error codes and messages related to donations and deposits for improved error handling.
=> Fix circular import and enhance error handling enums

src/entities/entities.ts
테스트 코드 짤때 `createDataSource`에 집어넣을 용도로 만들었습니다. 추후에 app.module에도 넣어도 좋을 것 같습니다.
=> feat(entities): 매번 entities 다 적기 귀찮아 모듈을 만들어버렸습니다

src/features/deposit/commands/upload-deposit.usecase.ts, src/features/deposit/deposit.controller.ts, src/features/deposit/deposit.service.ts, src/features/deposit/dto/create-deposit.dto.ts
Replace the existing DepositDto with CreateDepositDto to ensure proper serialization of deposit data during upload operations. Introduce CreateDepositDto with necessary validation rules.
=> Hotfix: Update deposit DTO for serialization

src/features/deposit/domain/events/deposit-delete.saga.spec.ts, src/features/donation/commands/delete-donation.usecase.spec.ts, src/features/donation/domain/events/donation-event-handler.integration.spec.ts, src/features/donation/domain/events/donation-event-handler.spec.ts
- **fix(deposit-delete-saga): resolved dependency problems**
- **fix(delete-donation.spec): Remove unused event testing & Add missing usecase param**
- **fix(donation-event-handler.integration): Add missing param for event**
- **fix(donation-event-handler.spec): Add missing param for event**
=> Fix failing tests

src/features/funding/funding.service.ts
- 비회원 펀딩 리스트 조회 버그 수정
> 비회원의 경우, user를 넘겨받지 않아서 user.userId가 존재하지 않아 발생하던 버그 수정
=> fix: fix bug of read funding list from non-member WISH-461
